### ISSUE TITLE
Genome2D-ContextUnity/build.hxml

### ISSUE THREAD

**Issue by peteshand** [pshtif/Genome2D-ContextUnity#1]
Should I be able to build Genome2D-ContextUnity/build.hxml to test your Unity Context?

I'm getting the following error:
/haxe/libs/box2d/1,2,3/box2D/dynamics/B2DebugDraw.hx:25: characters 8-28 : You cannot access the flash package while targeting cs (for flash.display.Sprite)
/haxe/libs/box2d/1,2,3/box2D/dynamics/controllers/B2Controller.hx:23: characters 8-34 :     referenced here
/haxe/libs/box2d/1,2,3/box2D/dynamics/B2World.hx:40: characters 8-47 :     referenced here
examples/com/genome2d/examples/PhysicsExample.hx:29: characters 8-30 :     referenced here
(unknown) :     referenced here

If I comment out the box2d line in build.xml I then get the follwo error.
../Genome2D-Spine/src/spinehaxe/animation/AnimationState.hx:62: characters 25-69 : Warning : No overload found for this constructor call

Is this the correct build.hxml, or should I be looking somewhere else?

**Comment by pshtif** [comment]
Hi yep sorry this is a problem inside Box2D which is not part of Genome2D obviously and since they don't have abstraction over sprite they are tied to flash packages, just remove it or change all Sprite stuff inside Box2D like I did to Dynamic to make it work and compile.

As for the AnimationState that is part of the Spine guys code, but that is just a warning it will compile without problem.

It is a correct build, it generates all the C# stuff, to run it you need to go inside the Unity TestBed project in the codebase and just run it inside unity. Create a game object with any of the Examples as a component.

**Comment by pshtif** [comment]
I decided to do a Dev Cast on youtube this weekend how to run the Unity context, for all guys that want to try it out as I got approached by a few of you over various channels.  So if you still have issues check it out later this week.

**Comment by peteshand** [comment]
Cool, thanks for the pointers, have the examples running.
Good to know about the dev cast 👍
